pipeline {
    agent any

    stages {
        stage('Build') {
        steps {
            script {
            sh 'echo "Building Stage and more test"'
                }
            }
        }

        stage('Test') {
        steps {
            script {
            sh 'echo "Testing Stage"'
                }
            }
        }

        stage('Deploy') {
        steps {
            script {
            sh 'echo "Deploying Stage"'
                }
            }
        }

        stage('Package') {
        steps {
            script {
            sh 'echo "Packaging Stage"'
                }
            }
        }

        stage('Clean Up') {
        steps {
            script {
            sh 'echo "Cleaing up Stage"'
                }
            }
        }
    }
}