---
# tasks file for apacheRole
- name: Install apache
  become: yes
  apt:
    name: apache2
    state: present


- name: start apache2 service
  become: yes
  service:
    name: apache2
    state: started